# Generated by Django 3.2.25 on 2024-08-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_name', models.CharField(max_length=100, verbose_name='DB명')),
                ('host', models.CharField(max_length=255, verbose_name='호스트')),
                ('port', models.IntegerField(verbose_name='포트')),
                ('username', models.CharField(max_length=100, verbose_name='사용자명')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='추가 옵션')),
                ('bucket_path', models.CharField(max_length=300, verbose_name='bucket경로')),
            ],
            options={
                'verbose_name': '[DB] 데이터베이스',
                'verbose_name_plural': '[DB] 데이터베이스',
                'db_table': 'sf_databases',
            },
        ),
        migrations.CreateModel(
            name='LoadInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('interval_type', models.CharField(max_length=100, verbose_name='스케줄 타입')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadinterval_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[스케줄] 로드 주기',
                'verbose_name_plural': '[스케줄] 로드 주기',
                'db_table': 'sf_load_interval',
            },
        ),
        migrations.CreateModel(
            name='LoadMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('load_type', models.CharField(max_length=100, verbose_name='로드 방법')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadmethod_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[스케줄] 로드 방법',
                'verbose_name_plural': '[스케줄] 로드 방법',
                'db_table': 'sf_load_method',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('table_name', models.CharField(max_length=100, verbose_name='테이블 물리명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='테이블 논리명')),
                ('cdc_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='CDC 여부')),
                ('sql_where', models.TextField(blank=True, null=True, verbose_name='SQL WHERE 절')),
                ('id_db', models.ForeignKey(blank=True, db_column='id_db', default=7, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.databases', verbose_name='DB명')),
                ('id_load_interval', models.ForeignKey(blank=True, db_column='id_load_interval', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.loadinterval', verbose_name='로드 주기')),
                ('id_load_method', models.ForeignKey(blank=True, db_column='id_load_method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.loadmethod', verbose_name='로드 방법')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tables_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[DB] 테이블',
                'verbose_name_plural': '[DB] 테이블',
                'db_table': 'sf_tables',
            },
        ),
        migrations.CreateModel(
            name='DbEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_env_name', models.CharField(max_length=100, verbose_name='운영/테스트/개발')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dbenv_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[DB] 운영/테스트/개발',
                'verbose_name_plural': '[DB] 운영/테스트/개발',
                'db_table': 'sf_db_env',
            },
        ),
        migrations.CreateModel(
            name='DataTypesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('datatype_mapping_name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypesmapping_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[DB] 매핑 데이터 타입',
                'verbose_name_plural': '[DB] 매핑 데이터 타입',
                'db_table': 'sf_datatypes_mapping',
            },
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('datatype_name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datatypes_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[DB] 데이터 타입',
                'verbose_name_plural': '[DB] 데이터 타입',
                'db_table': 'sf_datatypes',
            },
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('db_type_name', models.CharField(max_length=100, unique=True, verbose_name='DB 종류')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databasetype_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[DB] 데이터베이스 종류',
                'verbose_name_plural': '[DB] 데이터베이스 종류',
                'db_table': 'sf_database_types',
            },
        ),
        migrations.AddField(
            model_name='databases',
            name='id_databasetype',
            field=models.ForeignKey(db_column='id_databasetype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.databasetype', verbose_name='DB 종류'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_dbenv',
            field=models.ForeignKey(db_column='id_dbenv', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.dbenv', verbose_name='운영/테스트/개발'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('column_name', models.CharField(max_length=100, verbose_name='컬럼 물리명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='컬럼 논리명')),
                ('id_datatypes', models.ForeignKey(db_column='id_datatypes', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.datatypes', verbose_name='데이터 타입')),
                ('id_datatypes_mapping', models.ForeignKey(db_column='id_datatypes_mapping', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.datatypesmapping', verbose_name='매핑 타입')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='columns_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('id_table', models.ForeignKey(db_column='id_table', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.tables', verbose_name='테이블')),
            ],
            options={
                'verbose_name': '[DB] 컬럼',
                'verbose_name_plural': '[DB] 컬럼',
                'db_table': 'sf_columns',
            },
        ),
    ]
