# Generated by Django 3.2.25 on 2024-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns',
            options={'verbose_name': '대상 컬럼 리스트', 'verbose_name_plural': '대상 컬럼 리스트'},
        ),
        migrations.AlterModelOptions(
            name='databases',
            options={'verbose_name': '대상 데이터베이스 리스트', 'verbose_name_plural': '대상 데이터베이스 리스트'},
        ),
        migrations.AlterModelOptions(
            name='databasetype',
            options={'verbose_name': '[코드] 데이터베이스 종류', 'verbose_name_plural': '[코드] 데이터베이스 종류'},
        ),
        migrations.AlterModelOptions(
            name='datatypes',
            options={'verbose_name': '[코드] 데이터 타입', 'verbose_name_plural': '[코드] 데이터 타입'},
        ),
        migrations.AlterModelOptions(
            name='datatypesmapping',
            options={'verbose_name': '[코드] 매핑 데이터 타입', 'verbose_name_plural': '[코드] 매핑 데이터 타입'},
        ),
        migrations.AlterModelOptions(
            name='dbenv',
            options={'verbose_name': '[코드] 운영/테스트/개발', 'verbose_name_plural': '[코드] 운영/테스트/개발'},
        ),
        migrations.AlterModelOptions(
            name='loadinterval',
            options={'verbose_name': '[코드] 로드 주기', 'verbose_name_plural': '[코드] 로드 주기'},
        ),
        migrations.AlterModelOptions(
            name='loadmethod',
            options={'verbose_name': '[코드] 로드 방법', 'verbose_name_plural': '[코드] 로드 방법'},
        ),
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': '대상 테이블 리스트', 'verbose_name_plural': '대상 테이블 리스트'},
        ),
        migrations.RemoveField(
            model_name='columns',
            name='id_datatypes_mapping',
        ),
        migrations.AddField(
            model_name='columns',
            name='partition_yn',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Partition 여부'),
        ),
        migrations.AddField(
            model_name='columns',
            name='pk_yn',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='PK 여부'),
        ),
        migrations.AddField(
            model_name='databases',
            name='cdc_bucket_path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CDC bucket경로'),
        ),
        migrations.AddField(
            model_name='tables',
            name='catalog_db_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catalog DB명'),
        ),
        migrations.AddField(
            model_name='tables',
            name='catalog_table_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catalog Table명'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_executor_cores',
            field=models.BigIntegerField(default=1, verbose_name='spark : executor-cores'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_executor_memory',
            field=models.BigIntegerField(default=4, verbose_name='spark : executor-memory(gb)'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_num_executors',
            field=models.BigIntegerField(default=1, verbose_name='spark : num-executors'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_numpartitions',
            field=models.BigIntegerField(default=1, verbose_name='spark : numpartitions'),
        ),
    ]
