# Generated by Django 5.1 on 2024-08-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '[DB] 데이터 타입',
                'verbose_name_plural': '[DB] 데이터 타입',
                'db_table': 'sf_datatypes',
            },
        ),
        migrations.CreateModel(
            name='DataTypesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='데이터 타입 명')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '[DB] 매핑 데이터 타입',
                'verbose_name_plural': '[DB] 매핑 테이터 타입',
                'db_table': 'sf_datatypes_mapping',
            },
        ),
        migrations.CreateModel(
            name='DbEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=100, verbose_name='운영/테스트/개발')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '[DB] 운영/테스트/개발',
                'verbose_name_plural': '[DB] 운영/테스트/개발',
                'db_table': 'sf_db_env',
            },
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100, verbose_name='DB명')),
                ('db_type', models.CharField(max_length=100, verbose_name='DB타입')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('id_dbenv', models.ForeignKey(db_column='id_dbenv', on_delete=django.db.models.deletion.CASCADE, to='smartflow.dbenv', verbose_name='운영/테스트/개발')),
            ],
            options={
                'verbose_name': '[DB] 데이터베이스',
                'verbose_name_plural': '[DB] 데이터베이스',
                'db_table': 'sf_databases',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, verbose_name='테이블 Owner')),
                ('table_name', models.CharField(max_length=100, verbose_name='테이블 물리명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='테이블 논리명')),
                ('cdc_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='CDC 여부')),
                ('sql_where', models.TextField(blank=True, null=True, verbose_name='SQL WHERE 절')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('id_db', models.ForeignKey(blank=True, db_column='id_service', default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartflow.databases', verbose_name='서비스')),
            ],
            options={
                'verbose_name': '[DB] 테이블',
                'verbose_name_plural': '[DB] 테이블',
                'db_table': 'sf_tables',
            },
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100, verbose_name='컬럼 물리명')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='컬럼 논리명')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('id_datatypes', models.ForeignKey(db_column='id_datatypes', on_delete=django.db.models.deletion.CASCADE, to='smartflow.datatypes', verbose_name='데이터 타입')),
                ('id_datatypes_mapping', models.ForeignKey(db_column='id_datatypes_mapping', on_delete=django.db.models.deletion.CASCADE, to='smartflow.datatypesmapping', verbose_name='매핑 타입')),
                ('id_table', models.ForeignKey(db_column='id_table', on_delete=django.db.models.deletion.CASCADE, to='smartflow.tables', verbose_name='테이블')),
            ],
            options={
                'verbose_name': '[DB] 컬럼',
                'verbose_name_plural': '[DB] 컬럼',
                'db_table': 'sf_columns',
            },
        ),
    ]
