# Generated by Django 5.1 on 2024-08-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0002_datatypes_datatypesmapping_dbenv_databases_tables_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
