# Generated by Django 3.2.25 on 2024-09-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0002_auto_20240828_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databases',
            name='password',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='username',
        ),
        migrations.AddField(
            model_name='tables',
            name='use_yn',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='id_datatypes',
            field=models.ForeignKey(blank=True, db_column='id_datatypes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.datatypes', verbose_name='데이터 타입'),
        ),
    ]
