# Generated by Django 5.1 on 2024-08-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0003_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='columns',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypesmapping',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypesmapping',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='dbenv',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='dbenv',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='mod_dtm',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='reg_dtm',
        ),
    ]
