# Generated by Django 3.2.25 on 2024-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0003_auto_20240905_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='spark_fetchsize',
            field=models.BigIntegerField(blank=True, default=10000, null=True, verbose_name='Spark : fetchsize'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_lowerBound',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : lowerBound'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_partitionColumn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : partitionColumn'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_query',
            field=models.TextField(blank=True, null=True, verbose_name='BigTable : Query'),
        ),
        migrations.AddField(
            model_name='tables',
            name='spark_upperBound',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spark : upperBound'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='spark_executor_cores',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : executor-cores'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='spark_executor_memory',
            field=models.BigIntegerField(blank=True, default=4, null=True, verbose_name='Spark : executor-memory(gb)'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='spark_num_executors',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : num-executors'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='spark_numpartitions',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Spark : numPartitions'),
        ),
    ]
