# Generated by Django 5.1 on 2024-08-25 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0004_remove_columns_mod_dtm_remove_columns_reg_dtm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatypesmapping',
            options={'verbose_name': '[DB] 매핑 데이터 타입', 'verbose_name_plural': '[DB] 매핑 데이터 타입'},
        ),
        migrations.AddField(
            model_name='columns',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='columns',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='columns',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='columns',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='databases',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='databases',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='databases',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datatypes',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='datatypes',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datatypesmapping',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='datatypesmapping',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='datatypesmapping',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='datatypesmapping',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbenv',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='dbenv',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='dbenv',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='dbenv',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tables',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='tables',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='tables',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
        migrations.AddField(
            model_name='tables',
            name='reg_dtm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일자'),
            preserve_default=False,
        ),
    ]
