# Generated by Django 5.1.1 on 2024-09-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0004_auto_20240905_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='databasetype',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='datatypesmapping',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='dbenv',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='loadinterval',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='loadmethod',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
    ]
