# Generated by Django 5.1 on 2024-08-25 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0005_alter_datatypesmapping_options_columns_id_mod_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='datatypesmapping',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='dbenv',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='id_reg_user',
            field=models.ForeignKey(blank=True, db_column='id_reg_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_reg_users', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
