# Generated by Django 3.2.25 on 2024-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0005_alter_columns_id_mod_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='패스워드'),
        ),
        migrations.AddField(
            model_name='databases',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자명'),
        ),
    ]
