# Generated by Django 3.2.25 on 2024-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0006_auto_20240907_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SID/DB명'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='db_name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
