# Generated by Django 5.1 on 2024-08-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0006_alter_columns_id_reg_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='db_type',
            field=models.CharField(max_length=100, verbose_name='DB종류'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='id_db',
            field=models.ForeignKey(blank=True, db_column='id_db', default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartflow.databases', verbose_name='DB명'),
        ),
    ]
