# Generated by Django 5.1 on 2024-08-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0007_alter_databases_db_type_alter_tables_id_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='owner',
        ),
    ]
