# Generated by Django 5.1 on 2024-08-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0008_remove_tables_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='columns',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='databases',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='datatypesmapping',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='datatypesmapping',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='dbenv',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='dbenv',
            name='reg_dtm',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='id_reg_user',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='reg_dtm',
        ),
    ]
