# Generated by Django 3.2.25 on 2024-09-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0008_auto_20240907_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='datatypes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='데이터 타입'),
        ),
    ]
