# Generated by Django 5.1 on 2024-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0009_remove_columns_id_reg_user_remove_columns_reg_dtm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='host',
            field=models.CharField(default='0.0.0.0', max_length=255, verbose_name='호스트'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='추가 옵션'),
        ),
        migrations.AddField(
            model_name='databases',
            name='password',
            field=models.CharField(default='test', max_length=100, verbose_name='비밀번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='port',
            field=models.IntegerField(default=3306, verbose_name='포트'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='schema_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='스키마명'),
        ),
        migrations.AddField(
            model_name='databases',
            name='username',
            field=models.CharField(default='test', max_length=100, verbose_name='사용자명'),
            preserve_default=False,
        ),
    ]
