# Generated by Django 3.2.25 on 2024-09-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0010_rename_datatypes_columns_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns',
            name='id_datatypes',
        ),
    ]
