# Generated by Django 5.1 on 2024-08-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0010_databases_host_databases_options_databases_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='DB 종류')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '[DB] 종류',
                'verbose_name_plural': '[DB] 종류',
                'db_table': 'sf_database_types',
            },
        ),
        migrations.RemoveField(
            model_name='databases',
            name='db_type',
        ),
        migrations.AddField(
            model_name='databases',
            name='id_databasetype',
            field=models.ForeignKey(db_column='id_databasetype', null=True, on_delete=django.db.models.deletion.CASCADE, to='smartflow.databasetype', verbose_name='DB 종류'),
        ),
    ]
