# Generated by Django 5.1 on 2024-08-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0011_databasetype_remove_databases_db_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetype',
            name='id_mod_user',
            field=models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='databasetype',
            name='mod_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일자'),
        ),
    ]
