# Generated by Django 5.1 on 2024-08-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0012_databasetype_id_mod_user_databasetype_mod_dtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_type', models.CharField(max_length=100, verbose_name='스케줄 타입')),
            ],
            options={
                'verbose_name': '[스케줄] 로드 주기',
                'verbose_name_plural': '[스케줄] 로드 주기',
                'db_table': 'sf_load_interval',
            },
        ),
        migrations.AlterModelOptions(
            name='databasetype',
            options={'verbose_name': '[DB] 데이터베이스 종류', 'verbose_name_plural': '[DB] 데이터베이스 종류'},
        ),
        migrations.AddField(
            model_name='tables',
            name='id_load_interval',
            field=models.ForeignKey(blank=True, db_column='id_load_interval', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartflow.loadinterval', verbose_name='로드 주기'),
        ),
    ]
