# Generated by Django 5.1 on 2024-08-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0014_loadinterval_id_mod_user_loadinterval_mod_dtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databases',
            name='schema_name',
        ),
    ]
