# Generated by Django 5.1 on 2024-08-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartflow', '0015_remove_databases_schema_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasetype',
            old_name='name',
            new_name='db_type_name',
        ),
        migrations.RenameField(
            model_name='datatypes',
            old_name='name',
            new_name='datatype_name',
        ),
        migrations.RenameField(
            model_name='datatypesmapping',
            old_name='name',
            new_name='datatype_mapping_name',
        ),
        migrations.RenameField(
            model_name='dbenv',
            old_name='env_name',
            new_name='db_env_name',
        ),
        migrations.RemoveField(
            model_name='databasetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='description',
        ),
        migrations.AddField(
            model_name='databases',
            name='bucket_path',
            field=models.CharField(default='datalake_path', max_length=300, verbose_name='bucket경로'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='columns',
            name='id_datatypes',
            field=models.ForeignKey(db_column='id_datatypes', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.datatypes', verbose_name='데이터 타입'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='id_datatypes_mapping',
            field=models.ForeignKey(db_column='id_datatypes_mapping', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.datatypesmapping', verbose_name='매핑 타입'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='id_table',
            field=models.ForeignKey(db_column='id_table', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.tables', verbose_name='테이블'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='id_databasetype',
            field=models.ForeignKey(db_column='id_databasetype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.databasetype', verbose_name='DB 종류'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='id_dbenv',
            field=models.ForeignKey(db_column='id_dbenv', on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.dbenv', verbose_name='운영/테스트/개발'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='id_db',
            field=models.ForeignKey(blank=True, db_column='id_db', default=7, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.databases', verbose_name='DB명'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='id_load_interval',
            field=models.ForeignKey(blank=True, db_column='id_load_interval', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.loadinterval', verbose_name='로드 주기'),
        ),
        migrations.CreateModel(
            name='LoadMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_dtm', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('load_type', models.CharField(max_length=100, verbose_name='로드 방법')),
                ('id_mod_user', models.ForeignKey(blank=True, db_column='id_mod_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mod_users', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '[스케줄] 로드 방법',
                'verbose_name_plural': '[스케줄] 로드 방법',
                'db_table': 'sf_load_method',
            },
        ),
        migrations.AddField(
            model_name='tables',
            name='id_load_method',
            field=models.ForeignKey(blank=True, db_column='id_load_method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartflow.loadmethod', verbose_name='로드 방법'),
        ),
    ]
